// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQb9z4OioEJevnkAFiZMCIZ4TaZqTX7Ac',
    appId: '1:695819207315:web:b3706a8b6d4f1fdb2d0366',
    messagingSenderId: '695819207315',
    projectId: 'kaon-df902',
    authDomain: 'kaon-df902.firebaseapp.com',
    storageBucket: 'kaon-df902.appspot.com',
    measurementId: 'G-S0VS4WN54B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSjJUautw_AnCRaFpM6zv2qI_iBsxBnV4',
    appId: '1:695819207315:android:9ef186e586babad42d0366',
    messagingSenderId: '695819207315',
    projectId: 'kaon-df902',
    storageBucket: 'kaon-df902.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLaFkHfSvmtxxgy-3yo_tgbhCYnsclKnQ',
    appId: '1:695819207315:ios:99b201a31fa451b72d0366',
    messagingSenderId: '695819207315',
    projectId: 'kaon-df902',
    storageBucket: 'kaon-df902.appspot.com',
    iosBundleId: 'com.kaon.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLaFkHfSvmtxxgy-3yo_tgbhCYnsclKnQ',
    appId: '1:695819207315:ios:3e1d23b879c9eccc2d0366',
    messagingSenderId: '695819207315',
    projectId: 'kaon-df902',
    storageBucket: 'kaon-df902.appspot.com',
    iosBundleId: 'com.example.kaonApp.RunnerTests',
  );
}
